name: ARM Tests

on: 
  workflow_dispatch:

jobs:
  debug:
    name: debug
    runs-on: ubuntu-22.04-arm

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: debug
        run: | 
          printenv
          whoami
